### ISSUE TITLE
are you sure these two colabs working?

### ISSUE THREAD

**Issue by jjiikkkk** [camenduru/InvokeAI-colab#12]
no image comes out

**Comment by ShashwatDubey99** [comment]
yeah you have to reload every time you generate an image

**Comment by vinMoreiraHenrique** [comment]
Hi guys, how are you? the 2 collabs right there is not working properly, we need to refresh the page everytime i put to generate

**Comment by ShashwatDubey99** [comment]
> Hi guys, how are you? the 2 collabs right there is not working properly, we need to refresh the page everytime i put to generate

You can just downgrade python-socketio using !pip install python-socketio==5.9.0

**Comment by camenduru** [comment]
thanks @ShashwatDubey99 ❤
