### ISSUE TITLE
Permanent Fix For Colab 

### ISSUE THREAD

**Issue by ShashwatDubey99** [camenduru/InvokeAI-colab#14]
Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?

**Comment by ShashwatDubey99** [comment]
By banning I mean like sd Webui , comfy ui , etc

**Comment by Kingal20000** [comment]
> Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?

Hi, i thinking can we fork the main software and change name or change codes for that add git for colab

**Comment by Kingal20000** [comment]
> Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?

I don't think so, many people use invoke ai because it has a RAM increase bug, after a few minutes the RAM usage reaches the maximum, then it jumps out

**Comment by ShashwatDubey99** [comment]
I am currently tryi

> > Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> > They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?
> 
> Hi, i thinking can we fork the main software and change name or change codes for that add git for colab

Yeah I am currently trying to this thing with comfy ui , as it has the smallest file number , but I am not sure it will work or not do you know for sure it works or not

**Comment by Kingal20000** [comment]
> I am currently tryi
> 
> > > Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> > > They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?
> > 
> > Hi, i thinking can we fork the main software and change name or change codes for that add git for colab
> 
> Yeah I am currently trying to this thing with comfy ui , as it has the smallest file number , but I am not sure it will work or not do you know for sure it works or not

No, I don't know what method Google uses to find it, but I think it's the use name, because stable diffusion can be done by yourself simple cell, there's no problem, I think the same.

**Comment by ShashwatDubey99** [comment]
> > I am currently tryi
> > > > Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> > > > They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?
> > > 
> > > 
> > > Hi, i thinking can we fork the main software and change name or change codes for that add git for colab
> > 
> > 
> > Yeah I am currently trying to this thing with comfy ui , as it has the smallest file number , but I am not sure it will work or not do you know for sure it works or not
> 
> No, I don't know what method Google uses to find it, but I think it's the use name, because stable diffusion can be done by yourself simple cell, there's no problem, I think the same.
hey , i made it but not sure , would you mind trying it yourself , here is the link [https://colab.research.google.com/drive/1wJ3zQYHkpFFg_NexDaLtgVWpth7lcYww?usp=sharing]
, and first you have download the replace file ShiroUI.zip in your drive and mount your drive
[https://drive.google.com/file/d/1U32SGSslJ52hxyiFMX-5VjK45SAYOpP5/view?usp=share_link](url)

**Comment by ShashwatDubey99** [comment]
forget it its not working

**Comment by ShashwatDubey99** [comment]
really anyone doesn't know how google is terminating and identifying we are using comfy ui or other ui ?

**Comment by ShashwatDubey99** [comment]
> > Hi guys colab can ban invoke ai too , anytime they wants if this colab will be used by many people .
> > They will just ban the keyword invoke ai , Anyone have an idea for fixing it ?
> 
> I don't think so, many people use invoke ai because it has a RAM increase bug, after a few minutes the RAM usage reaches the maximum, then it jumps out

Hey I forgot to tell you highram usage has a fix you can add argument - - max_cache_size 2, 3 or 4 to prevent it

**Comment by ShashwatDubey99** [comment]
Finally i fixed it (COMFY)
